#!/bin/bash
# Stripe Webhook Testing Commands
# Make executable with: chmod +x test-webhooks.sh

echo "🔔 Stripe Webhook Test Commands"
echo "=================================="
echo ""
echo "📋 Quick Setup:"
echo "1. Install Stripe CLI: https://stripe.com/docs/stripe-cli"
echo "2. Login: stripe login"
echo "3. Forward webhooks: stripe listen --forward-to http://localhost:8080/api/stripe/webhook"
echo "4. Copy the webhook secret to your .env file"
echo ""
echo "🧪 Test Commands:"
echo ""
echo "# Test successful payment"
echo "stripe trigger payment_intent.succeeded"
echo ""
echo "# Test failed payment"
echo "stripe trigger payment_intent.payment_failed"
echo ""
echo "# Test new subscription"
echo "stripe trigger customer.subscription.created"
echo ""
echo "# Test subscription update"
echo "stripe trigger customer.subscription.updated"
echo ""
echo "# Test subscription cancellation"
echo "stripe trigger customer.subscription.deleted"
echo ""
echo "# Test invoice paid"
echo "stripe trigger invoice.paid"
echo ""
echo "# Test invoice payment failed"
echo "stripe trigger invoice.payment_failed"
echo ""
echo "# Test refund"
echo "stripe trigger charge.refunded"
echo ""
echo "📊 View logs in your server console to see webhook events!"
echo ""
echo "💡 Tip: Run 'stripe listen --forward-to http://localhost:8080/api/stripe/webhook --print-json'"
echo "   to see the full JSON payload of each webhook event."
